<template>
  <div>
    <div v-if="recipe">
      <div class="flex gap-3 justify-between flex-wrap frame">
        <div class="img"></div>
        <div class="flex-1 flex flex-col">
          <h1>{{ recipe.title }}</h1>
          <h2 v-if="recipe.subtitle">{{ recipe.subtitle }}</h2>
          <a v-if="recipe.source" :href="recipe.source" target="_blank">
            <i class="icon i-hugeicons-link-02"></i>
            {{ recipe.source_name ?? recipe.source }}
          </a>
          <div class="flex flex-wrap mt-5 gap-1">
            <ui-pin
              v-for="tag in recipe.tags"
              :text="tag.name"
              color="var(--primary-100)"
            />
          </div>
          <div class="flex flex-wrap mt-2 gap-1">
            <ui-pin>
              <i class="icon i-hugeicons-rice-bowl-01"></i>
              <span>{{ recipe.portions }} SERVINGS</span>
            </ui-pin>
            <ui-pin>
              <i class="icon i-hugeicons-time-02"></i>
              <span>20min</span>
            </ui-pin>
          </div>
          <recipes-ingredients-list
            v-if="recipe.ingredients.length > 0"
            @cancel="
              autor = undefined;
              recipe.ingredients = [];
            "
            @refresh="
              autor = undefined;
              recipe.ingredients = [];
              autoRecognize();
            "
            :autogenerated="autorecognized"
            v-model="recipe.portions"
            :ingredients="recipe.ingredients"
            class="flex-1 mt-3"
          />
          <ui-empty
            v-else
            @click="autoRecognize"
            class="mt-3 flex-1 min-h-xs"
            title="no ingredients"
            subtitle="click to autofill"
            :loading="autoRecognizePending"
            clickable
          />
        </div>
      </div>

      <section v-if="isLoggedIn" class="flex justify-end gap-2 mt-5">
        <ui-button @click="editOpen = true" icon="i-hugeicons-quill-write-02"
          >Edit</ui-button
        >
      </section>

      <section
        v-if="recipe.body"
        class="content mt-5"
        v-html="recipe.body"
      ></section>
      <ui-empty
        v-else
        transparent
        class="mt-3 min-h-md lg:min-h-xl"
        title="recipe is missing"
        subtitle="...shame&nbsp;on&nbsp;us!"
        icon="i-hugeicons-pot-02"
      />

      <Teleport to="body">
        <ui-modal ref="modal" v-if="editOpen" @closed="editOpen = false">
          <div class="min-h-lg flex flex-col">
            <h3 class="font-sans text-3xl font-500 pt-0 uppercase">
              {{ cloned.title }}
            </h3>
            <h4 class="mb-8 uppercase font-sans">{{ cloned.subtitle }}</h4>
            <recipes-form ref="form" v-model="cloned"></recipes-form>
            <div class="flex mt-auto pt-5 gap-2">
              <ui-button
                @click="() => edit(cloned)"
                color="success"
                icon="i-hugeicons-floppy-disk"
                >Save changes</ui-button
              >
              <ui-button
                @click="editOpen = false"
                color="secondary"
                icon="i-hugeicons-cancel-01"
                class="flex-1"
                >close</ui-button
              >
              <ui-button
                @click="resetClone"
                color="secondary"
                icon="i-hugeicons-refresh"
                class="flex-1"
              />
              <ui-button @click="prev" icon="i-hugeicons-arrow-left-double" />
              <ui-button @click="next" icon="i-hugeicons-arrow-right-double" />
            </div>
          </div>
        </ui-modal>
      </Teleport>

      <Teleport to="body">
        <ui-modal
          v-if="deleteOpen"
          @closed="deleteOpen = false"
          width-class="max-w-lg min-w-sm"
        >
          <h3 class="font-sans text-3xl font-500 uppercase mt-5">
            Confirm delete
          </h3>
          <h4 class="mb-8 uppercase font-sans">Are you really, really sure?</h4>
          <div class="flex my-4 gap-2 mb-0">
            <ui-button color="danger" width="100%" icon="i-hugeicons-delete-02"
              >delete</ui-button
            >
            <ui-button
              @click="deleteOpen = false"
              color="secondary"
              width="100%"
              icon="i-hugeicons-cancel-01"
              >cancel</ui-button
            >
          </div>
        </ui-modal>
      </Teleport>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { RecipesForm } from "#build/components";
import type { Recipe } from "@/types";
import { useLocalStorage, useSwipe } from "@vueuse/core";

const route = useRoute();
const { isLoggedIn } = useLogin();

const { addNotification } = useNotifications();

const {
  data: recipe,
  refresh,
  error,
} = await useFetch<Recipe>(`/api/recipes/${route.params.id}`);

if (error.value) {
  handleErrorRedirect(error.value);
}

const cloned = useLocalStorage(
  `autosave-recipe-${recipe.value?.id}`,
  JSON.parse(JSON.stringify(recipe.value))
);

const resetClone = () => {
  cloned.value = JSON.parse(JSON.stringify(recipe.value));
};

useHead({
  title: recipe.value?.title ?? "Recept",
});

const form = ref<InstanceType<typeof RecipesForm> | null>(null);

// interface ParseIngredient {
//   name: string;
//   count?: number;
//   unit?: string;
//   note?: string;
// }

const autorecognized = ref(false);
const autoRecognizePending = ref(false);
const autor = ref();
async function autoRecognize() {
  autoRecognizePending.value = true;
  try {
    const parsed = await wrappedFetch(
      `/api/recipes/${route.params.id}/parse`,
      {
        method: "POST",
        customNotification: {
          text: "AI is sleeping, try again later.",
          level: "error",
          icon: "i-hugeicons-ai-brain-01",
        }
      }
    );
  } finally {
    autoRecognizePending.value = false;
  }
}

const backgroundUrl = computed(
  () => recipe.value?.detail_image ?? "/notfound.jpg"
);
const background = computed(() => `url('${backgroundUrl.value}')`);

const deleteOpen = ref(false);

const { getIngredients } = useIngredients();
const { getTags } = useTags();

onMounted(async () => await getIngredients());
onMounted(async () => await getTags());

const next = () => {
  if (form.value) form.value.nextStep();
};

const prev = () => {
  if (form.value) form.value.previousStep();
};

const editOpen = ref(false);
const edit = async (data: Recipe) => {
  if (!form.value) {
    return;
  }

  await form.value.validate();
  if (form.value.hasErrors()) {
    addNotification({
      text: "Invalid form data",
      level: "error",
      icon: "i-hugeicons-bubble-chat-cancel",
    });
    return;
  }

  await wrappedFetch(`/api/recipes/${recipe.value?.id}`, {
    method: "PUT",
    body: data,
  });
  addNotification({
    text: "Recipe updated",
    level: "success",
    icon: "i-hugeicons-quill-write-02",
  });
  await refresh();
  cloned.value = JSON.parse(JSON.stringify(recipe.value));
  editOpen.value = false;
};

const modal = ref(null);
const { isSwiping, direction } = useSwipe(modal);
watch(isSwiping, (val, old) => {
  if (!old && val) {
    console.log(`STARTED SWIPE!!! ${direction.value}`);
    if (direction.value === "right") {
      prev();
    } else if (direction.value === "left") {
      next();
    }
  }
});
</script>

<style lang="css" scoped>
h1,
h2 {
  text-align: left;
}

h1 {
  --font-size: min(max(5dvw, 3rem), 5rem);
  font-size: var(--font-size);
  line-height: var(--font-size);
  font-weight: 400;
  text-transform: uppercase;
  text-wrap: wrap;
}

h2 {
  font-size: 2rem;
  text-transform: uppercase;
}

.img {
  flex: 1;
  border-radius: 0.5rem;
  background-image: v-bind("background");
  background-position: center;
  background-size: cover;
  aspect-ratio: 1;
  min-width: 20rem;
}

a:hover {
  text-decoration: underline;
}
</style>
