<template>
  <ui-card>
    <div class="flex h-full">
      <li class="flex-1">
        <ul v-for="item in ingredients">
          <span v-if="item.amount" class="text-xl">
            {{
              Math.ceil((item.amount / basePortions ?? 1) * 10 * modelValue) /
              10
            }}
          </span>
          <span v-if="item.unit">{{ item.unit.name }}</span>
          <span class="text-lg font-semibold ml-2 mr-1">{{
            item.ingredient.name
          }}</span>
          <span class="italic">{{ item.note }}</span>
        </ul>
      </li>
      <ui-portions-counter v-if="!autogenerated" v-model="modelValue" vertical />
      <div v-else class="flex flex-col gap-5 justify-center">
        <ui-button
          icon="i-hugeicons-checkmark-circle-01"
          link
          rounded
          @click="$emit('confirm')"
        />
        <ui-button
          icon="i-hugeicons-cancel-01"
          link
          rounded
          @click="$emit('cancel')"
        />
        <ui-button
          icon="i-hugeicons-refresh"
          link
          rounded
          @click="$emit('refresh')"
        />
      </div>
    </div>
  </ui-card>
</template>

<script setup lang="ts">
import type { IngredientItem } from "@/types/recipe";

interface Props {
  ingredients: IngredientItem[];
  autogenerated?: boolean;
}

const props = defineProps<Props>();
const emit = defineEmits(["refresh", "confirm", "cancel"]);

const modelValue = defineModel({ type: Number, required: true });

let basePortions = modelValue.value;
</script>

<style lang="css" scoped>
li {
  padding: 0;
  margin: 0;
  list-style: none;
}

ul {
  display: flex;
  align-items: center;
}

.cardd {
  min-height: 100rem;
}

ul::before {
  content: "";
  display: inline-block;
  width: 0.3rem;
  aspect-ratio: 1;
  background-color: var(--text-100);
  margin-right: 0.5rem;
  border-radius: 50%;
}

.ingredients {
  border-left: 3px solid var(--primary-100);
  padding-inline: 1rem;
  padding-block: 1rem;
  flex: 1;
}
</style>
